/**
 * NodeType enum
 * This enum is used to define the type of node in the syntax tree.
 */
export enum NodeType {
	CONSTANT = 'CONSTANT',
	VARIABLE = 'VARIABLE',
	PREDICATE = 'PREDICATE',
	FUNCTION = 'FUNCTION',
	QUANTIFIER = 'QUANTIFIER',
	QUANTIFIER_OPERATOR = 'QUANTIFIER_OPERATOR',
	NEGATION = 'NEGATION',
	PARENTHESES_BLOCK = 'PARENTHESES_BLOCK',
	PARENTHESIS = 'PARENTHESIS',
	BRACKETS_BLOCK = 'BRACKETS_BLOCK',
	BRACKET = 'BRACKET',
	BINARY_OPERATION = 'BINARY_OPERATION',
	TERM_LIST = 'TERM_LIST'
}
